#!/usr/bin/env bash
#
# Builds earlyinit and packages it into build/initramfs.cpio.gz.
#
# The archive is assembled from a spec file rather than from a directory tree,
# because two things we need cannot survive in git: an empty directory, and a
# device node. Generating them at build time is the only honest way to do it.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/build"
STAGING="$ROOT/initramfs"          # optional extra content, committed to the repo
OUT="$BUILD/initramfs.cpio.gz"

CC="${CC:-gcc}"
CFLAGS="${CFLAGS:--static -Wall -Wextra -O2}"

die() { echo "error: $*" >&2; exit 1; }

mkdir -p "$BUILD"

# --- compile earlyinit -----------------------------------------------------
# -static because there is no dynamic linker inside the initramfs: no ld.so,
# no libc.so. A dynamically linked PID 1 dies instantly with ENOENT.
[ -f "$ROOT/earlyinit/init.c" ] || die "earlyinit/init.c not found"
echo ">> compiling earlyinit"
$CC $CFLAGS -o "$BUILD/earlyinit" "$ROOT/earlyinit/init.c"

# --- write the cpio spec ---------------------------------------------------
SPEC="$BUILD/initramfs.spec"
{
  echo "# generated by build-initramfs.sh — do not edit"
  echo "file /init $BUILD/earlyinit 0755 0 0"
  echo "dir /proc 0755 0 0"
  echo "dir /sys 0755 0 0"
  echo "dir /dev 0755 0 0"
  echo "dir /mnt 0755 0 0"
  echo "dir /mnt/root 0755 0 0"
  # The kernel opens /dev/console to hand PID 1 its stdin/stdout/stderr, and it
  # does that BEFORE running /init, reading the node from this archive.
  # CONFIG_DEVTMPFS_MOUNT does not apply to initramfs, so mounting devtmpfs in
  # earlyinit is already too late. Without this line, every message earlyinit
  # prints goes nowhere and the boot looks silently dead.
  echo "nod /dev/console 0600 0 0 c 5 1"

  # Anything committed under initramfs/ gets folded in on top.
  if [ -d "$STAGING" ]; then
    ( cd "$STAGING"
      find . -mindepth 1 -type d -printf 'dir /%P 0755 0 0\n'
      find . -mindepth 1 -type f -printf "file /%P $STAGING/%P 0755 0 0\n"
    )
  fi
} > "$SPEC"

# --- pack ------------------------------------------------------------------
# Preferred: the kernel's own gen_init_cpio. It writes device nodes and root
# ownership straight into the archive as metadata, so nothing here needs to
# actually BE root — no sudo anywhere in this build.
GEN=""
for ksrc in "$BUILD"/linux-*/; do
  [ -f "$ksrc/usr/gen_init_cpio.c" ] || continue
  GEN="$BUILD/gen_init_cpio"
  if [ ! -x "$GEN" ] || [ "$ksrc/usr/gen_init_cpio.c" -nt "$GEN" ]; then
    echo ">> building gen_init_cpio from kernel source"
    $CC -O2 -o "$GEN" "$ksrc/usr/gen_init_cpio.c" || GEN=""
  fi
  [ -n "$GEN" ] && break
done

if [ -n "$GEN" ] && [ -x "$GEN" ]; then
  echo ">> packing with gen_init_cpio"
  "$GEN" "$SPEC" | gzip -9 > "$OUT"
elif command -v fakeroot >/dev/null; then
  # Fallback so you can build an initramfs before ever downloading kernel
  # source — useful for testing against your distro's /boot/vmlinuz.
  echo ">> gen_init_cpio unavailable, falling back to fakeroot + cpio"
  TREE="$BUILD/initramfs-root"
  rm -rf "$TREE"
  mkdir -p "$TREE"/{proc,sys,dev,mnt/root}
  cp "$BUILD/earlyinit" "$TREE/init"
  [ -d "$STAGING" ] && cp -a "$STAGING/." "$TREE/"
  fakeroot -- bash -c "
    set -e
    mknod '$TREE/dev/console' c 5 1
    chmod 0600 '$TREE/dev/console'
    chmod 0755 '$TREE/init'
    chown -R 0:0 '$TREE'
    cd '$TREE' && find . | cpio -o -H newc --quiet
  " | gzip -9 > "$OUT"
else
  die "need either kernel source (run build-kernel.sh) or fakeroot to build the archive"
fi

echo
echo "built  build/initramfs.cpio.gz  ($(du -h "$OUT" | cut -f1))"
